
export const SET_CONTACT_TO_EDIT = "SET_CONTACT_TO_EDIT";

const ACTION_TYPES = {
  //add
  ADD_CONTACT_ACTION: "ADD_CONTACT_ACTION",
  ADD_CONTACT_REQEST: "ADD_CONTACT_REQEST",
  ADD_CONTACT_SUCCESS: "ADD_CONTACT_SUCCESS",
  ADD_CONTACT_ERROR: "ADD_CONTACT_ERROR",

  //del
  DELETE_CONTACT_ACTION: "DELETE_CONTACT_ACTION",
  DELETE_CONTACT_REQEST: "DELETE_CONTACT_REQEST",
  DELETE_CONTACT_SUCCESS: "DELETE_CONTACT_SUCCESS",
  DELETE_CONTACT_ERROR: "DELETE_CONTACT_ERROR",

  //put
  PUT_CONTACT_ACTION: "PUT_CONTACT_ACTION",
  PUT_CONTACT_REQEST: "PUT_CONTACT_REQEST",
  PUT_CONTACT_SUCCESS: "PUT_CONTACT_SUCCESS",
  PUT_CONTACT_ERROR: "PUT_CONTACT_ERROR",

  //get
  GET_CONTACT_ACTION: "GET_CONTACT_ACTION",
  GET_CONTACT_REQEST: "GET_CONTACT_REQEST",
  GET_CONTACT_SUCCESS: "GET_CONTACT_SUCCESS",
  GET_CONTACT_ERROR: "GET_CONTACT_ERROR",
};

export default ACTION_TYPES;
