export const SET_CONTACT = "SET_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const ADD_CONTACT = "ADD_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const SET_CONTACT_TO_EDIT = "SET_CONTACT_TO_EDIT";
